# https://megalinter.io/configuration/

---
APPLY_FIXES: all
DISABLE:
  - SPELL
DISABLE_LINTERS:
  - MAKEFILE_CHECKMAKE
  - REPOSITORY_KICS
  - REPOSITORY_SECRETLINT
PLUGINS:
  - https://raw.githubusercontent.com/shiranr/linkcheck/main/mega-linter-plugin-linkcheck/linkcheck.megalinter-descriptor.yml

VALIDATE_ALL_CODEBASE: true
SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: false
PRINT_ALPACA: false
