---
name: CI

"on":
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

env:
  FPM_VERSION: 1.15.1

jobs:

  meta:
    name: Derive Build Metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Derive version string
        id: bin_version
        run: echo "bin_version=$(./.version.sh)" >> "$GITHUB_OUTPUT"
      - name: bin_version
        run: 'echo bin_version: ${{ steps.bin_version.outputs.bin_version }}'
      - name: Check if this is a running version tag update
        id: running_version_tag
        run: |
          if [ -z "${{ github.event.ref }}" ]; then
              echo "is_running_version_tag_update=false" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.event.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+$ ]]; then
              echo "is_running_version_tag_update=true" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.event.ref }}" =~ ^refs/tags/v[0-9]+$ ]]; then
              echo "is_running_version_tag_update=true" >> "$GITHUB_OUTPUT"
          else
              echo "is_running_version_tag_update=false" >> "$GITHUB_OUTPUT"
          fi
      - name: is_running_version_tag
        run: 'echo is_running_version_tag_update: ${{ steps.running_version_tag.outputs.is_running_version_tag_update }}'
    outputs:
      project_name: ${{ github.event.repository.name }}
      # nb. bin name uses underscores; project/repo name uses hyphens
      bin_name: _periodic_docker_pull
      bin_version: ${{ steps.bin_version.outputs.bin_version }}
      brewtap_owner: ${{ github.repository_owner }}
      brewtap_name: oss
      brewtap_formula_dir: formula
      is_prerelease: >-
            ${{
              steps.running_version_tag.outputs.is_running_version_tag_update != 'true' &&
              startsWith(github.ref, 'refs/tags/v') &&
                (contains(github.ref, '-alpha.')
                || contains(github.ref, '-beta.')
                || contains(github.ref, '-rc.'))
            }}
      is_release: >-
            ${{
              steps.running_version_tag.outputs.is_running_version_tag_update != 'true' &&
              startsWith(github.ref, 'refs/tags/v') &&
                !(contains(github.ref, '-alpha.')
                || contains(github.ref, '-beta.')
                || contains(github.ref, '-rc.'))
            }}
      is_pull_request: ${{ github.event_name == 'pull_request' }}
      is_running_version_tag_update: ${{ steps.running_version_tag.outputs.is_running_version_tag_update }}


  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run MegaLinter
        uses: oxsecurity/megalinter@v7
        env:
          # See https://megalinter.io/configuration and .mega-linter.yml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive MegaLinter artifacts
        if: ( !env.ACT && ( success() || failure() ) )
        uses: actions/upload-artifact@v3
        with:
          name: MegaLinter artifacts
          path: |
            megalinter-reports
            mega-linter.log


  binaries:
    name: Binaries
    needs: [lint, meta]
    if: needs.meta.outputs.is_running_version_tag_update != 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build binary
        run: make build

      - name: Prepare release artifacts
        id: prepare_artifacts
        run: |
          pushd out
          mkdir ./gh-release
          tar --transform='flags=r;s|.*|${{ needs.meta.outputs.bin_name }}|' \
            -czvf ./gh-release/${{ needs.meta.outputs.project_name }}-${{ needs.meta.outputs.bin_version }}-all.tar.gz \
            ./${{ needs.meta.outputs.bin_name }}-${{ needs.meta.outputs.bin_version }}-all
          echo "tgz_sha256_allarch=$(shasum -a 256 ./gh-release/${{ needs.meta.outputs.project_name }}-${{ needs.meta.outputs.bin_version }}-all.tar.gz  | cut -d " " -f 1)" >> "$GITHUB_OUTPUT"
          popd

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ needs.meta.outputs.project_name }} Binary Artifacts
          path: out/gh-release/*

    outputs:
      tgz_sha256_allarch: ${{ steps.prepare_artifacts.outputs.tgz_sha256_allarch }}


  release:
    name: GitHub (Pre)Release
    needs: [meta, binaries]
    if: >-
          needs.meta.outputs.is_release == 'true' ||
          needs.meta.outputs.is_prerelease == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Download binary
        uses: actions/download-artifact@v4.1.7
        with:
          name: ${{ needs.meta.outputs.project_name }} Binary Artifacts
          path: out

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: out/${{ needs.meta.outputs.project_name }}-*
          prerelease: ${{ needs.meta.outputs.is_prerelease == 'true' }}
          fail_on_unmatched_files: true
          generate_release_notes: true


  tags:
    name: Update Release Tags
    needs: [meta, release]
    if: needs.meta.outputs.is_release == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update running major/minor version tags
        uses: sersoft-gmbh/running-release-tags-action@v3
        with:
          fail-on-non-semver-tag: true
          create-release: false
          update-full-release: false


  homebrew:
    name: Update Homebrew Tap
    needs: [meta, binaries]
    if: needs.meta.outputs.is_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          path: src

      - name: Checkout ${{ needs.meta.outputs.brewtap_owner }}/${{ needs.meta.outputs.brewtap_name }} tap repo
        uses: actions/checkout@v4
        with:
          path: brewtap
          repository: ${{ needs.meta.outputs.brewtap_owner }}/homebrew-${{ needs.meta.outputs.brewtap_name }}
          token: ${{ secrets.HOMEBREW_RELEASER_PAT }}

      - name: Generate formula file
        run: |
          env \
            FORMULA_VERSION_NO_V="${{ needs.meta.outputs.bin_version }}" \
            FORMULA_TGZ_SHA256="${{ needs.binaries.outputs.tgz_sha256_allarch }}" \
            ./src/.formula.sh > ./brewtap/${{ needs.meta.outputs.brewtap_formula_dir }}/${{ needs.meta.outputs.project_name }}.rb

      - name: Commit and push to tap
        uses: EndBug/add-and-commit@v9
        with:
          cwd: ./brewtap
          add: './${{ needs.meta.outputs.brewtap_formula_dir }}/${{ needs.meta.outputs.project_name }}.rb'
          author_name: homebrew-releaser-bot
          author_email: homebrew-releaser-bot@users.noreply.github.com
          message: 'Add ${{ needs.meta.outputs.project_name }} v${{ needs.meta.outputs.bin_version }}'
          pathspec_error_handling: exitImmediately
          push: true
          github_token: ${{ secrets.HOMEBREW_RELEASER_PAT }}
